# Telegram频道推广配置
# [REWRITE 2025-10-10] 链接直接从推广链接.txt硬编码
# [FIX 2025-10-11] 移除概率控制，新增模板路径配置
version: "2.1.0"
last_updated: "2025-10-11"

# [FIX 2025-10-11] 基础软文模板路径
soft_promo_template_path: "C:\\Users\\beima\\Desktop\\BaiduSyncdisk\\Trx相关\\reddit账号\\基础软文模板.json"

# 核心策略
strategy:
  telegram_link_promotion: true
  # [DEPRECATED 2025-10-11] 以下概率控制已移除，现改为100%插入（由link_policy决定模式）
  # insertion_probability_by_intent:
  #   A: 0.70
  #   B: 0.40
  #   C: 0.60
  contextual_matching: true

# 第一组链接池: luntria.org (100个)
group_1_luntria:
  domain: "luntria.org"
  description: "通用工具和资源入口"

  onboarding:
    - "https://start.luntria.org/guide"
    - "https://begin.luntria.org/welcome"
    - "https://launch.luntria.org/next"
    - "https://enter.luntria.org/app"
    - "https://join.luntria.org/member"
    - "https://signup.luntria.org/free"
    - "https://access.luntria.org/now"
    - "https://connect.luntria.org/live"
    - "https://move.luntria.org/forward"
    - "https://step.luntria.org/into"

  tools:
    - "https://app.luntria.org/connect"
    - "https://apps.luntria.org/tools"
    - "https://tool.luntria.org/check"
    - "https://tools.luntria.org/convert"
    - "https://utility.luntria.org/scan"
    - "https://portal.luntria.org/login"
    - "https://panel.luntria.org/dashboard"
    - "https://console.luntria.org/manage"
    - "https://workspace.luntria.org/home"
    - "https://studio.luntria.org/create"

  help_support:
    - "https://help.luntria.org/info"
    - "https://helpdesk.luntria.org/support"
    - "https://support.luntria.org/faq"
    - "https://docs.luntria.org/setup"
    - "https://doc.luntria.org/guide"
    - "https://manual.luntria.org/start"
    - "https://knowledge.luntria.org/base"
    - "https://guide.luntria.org/steps"
    - "https://wiki.luntria.org/intro"
    - "https://learn.luntria.org/course"

  community:
    - "https://open.luntria.org/chat"
    - "https://community.luntria.org/topics"
    - "https://club.luntria.org/room"
    - "https://circle.luntria.org/forum"
    - "https://hub.luntria.org/start"
    - "https://group.luntria.org/join"
    - "https://forum.luntria.org/thread"
    - "https://board.luntria.org/discuss"
    - "https://channel.luntria.org/updates"
    - "https://network.luntria.org/global"

  news:
    - "https://news.luntria.org/latest"
    - "https://newsroom.luntria.org/update"
    - "https://press.luntria.org/release"
    - "https://status.luntria.org/check"
    - "https://status.luntria.org/live"
    - "https://report.luntria.org/weekly"
    - "https://insight.luntria.org/data"
    - "https://update.luntria.org/patch"
    - "https://updates.luntria.org/version"
    - "https://info.luntria.org/about"

  auth_security:
    - "https://auth.luntria.org/teng"
    - "https://auth.luntria.org/verify"
    - "https://secure.luntria.org/access"
    - "https://security.luntria.org/alert"
    - "https://safe.luntria.org/entry"
    - "https://account.luntria.org/profile"
    - "https://accounts.luntria.org/manage"
    - "https://id.luntria.org/connect"
    - "https://identity.luntria.org/verify"
    - "https://login.luntria.org/home"

  commerce:
    - "https://shop.luntria.org/cart"
    - "https://store.luntria.org/buy"
    - "https://market.luntria.org/deal"
    - "https://sale.luntria.org/today"
    - "https://promo.luntria.org/offer"
    - "https://promos.luntria.org/deals"
    - "https://deal.luntria.org/discount"
    - "https://offers.luntria.org/special"
    - "https://business.luntria.org/start"
    - "https://partner.luntria.org/join"

  events:
    - "https://event.luntria.org/register"
    - "https://events.luntria.org/live"
    - "https://meet.luntria.org/online"
    - "https://meeting.luntria.org/agenda"
    - "https://session.luntria.org/info"
    - "https://webinar.luntria.org/join"
    - "https://conference.luntria.org/schedule"
    - "https://summit.luntria.org/global"
    - "https://expo.luntria.org/virtual"
    - "https://campaign.luntria.org/launch"

  testing:
    - "https://beta.luntria.org/try"
    - "https://demo.luntria.org/live"
    - "https://lab.luntria.org/test"
    - "https://labs.luntria.org/preview"
    - "https://test.luntria.org/page"
    - "https://testing.luntria.org/feature"
    - "https://sample.luntria.org/check"
    - "https://trial.luntria.org/start"
    - "https://sandbox.luntria.org/play"
    - "https://preview.luntria.org/view"

  resources:
    - "https://service.luntria.org/contact"
    - "https://services.luntria.org/info"
    - "https://resource.luntria.org/files"
    - "https://resources.luntria.org/tools"
    - "https://download.luntria.org/app"
    - "https://downloads.luntria.org/package"
    - "https://library.luntria.org/data"
    - "https://content.luntria.org/view"
    - "https://assets.luntria.org/image"
    - "https://cdn.luntria.org/file"

# 第二组链接池: GitHub Pages能源租赁
group_2_energy:
  domain: "github.io"
  description: "TRX能源租赁专业服务"

  trxenergy:
    core:
      - "https://trxenergy.github.io/energy/"
      - "https://trxenergy.github.io/power/"
      - "https://trxenergy.github.io/rent/"
      - "https://trxenergy.github.io/fee/"
      - "https://trxenergy.github.io/usdt/"
    extended:
      - "https://trxenergy.github.io/boost/"
      - "https://trxenergy.github.io/chain/"
      - "https://trxenergy.github.io/charge/"
      - "https://trxenergy.github.io/community/"
      - "https://trxenergy.github.io/connect/"
      - "https://trxenergy.github.io/credit/"
      - "https://trxenergy.github.io/earn/"
      - "https://trxenergy.github.io/future/"
      - "https://trxenergy.github.io/global/"
      - "https://trxenergy.github.io/growth/"
      - "https://trxenergy.github.io/join/"
      - "https://trxenergy.github.io/lease/"
      - "https://trxenergy.github.io/mine/"
      - "https://trxenergy.github.io/network/"
      - "https://trxenergy.github.io/node/"
      - "https://trxenergy.github.io/official/"
      - "https://trxenergy.github.io/pool/"
      - "https://trxenergy.github.io/portal/"
      - "https://trxenergy.github.io/release/"
      - "https://trxenergy.github.io/saving/"
      - "https://trxenergy.github.io/secure/"
      - "https://trxenergy.github.io/smart/"
      - "https://trxenergy.github.io/stake/"
      - "https://trxenergy.github.io/update/"
      - "https://trxenergy.github.io/wallet/"

  trxrent:
    core:
      - "https://trxrent.github.io/rent"
      - "https://trxrent.github.io/energy"
      - "https://trxrent.github.io/power"
      - "https://trxrent.github.io/lowfee"
      - "https://trxrent.github.io/usdt"
    extended:
      - "https://trxrent.github.io/bandwidth"
      - "https://trxrent.github.io/freeze"
      - "https://trxrent.github.io/unfreeze"
      - "https://trxrent.github.io/saving"
      - "https://trxrent.github.io/fast"
      - "https://trxrent.github.io/global"
      - "https://trxrent.github.io/tron"
      - "https://trxrent.github.io/wallet"
      - "https://trxrent.github.io/recharge"
      - "https://trxrent.github.io/gas"
      - "https://trxrent.github.io/instant"
      - "https://trxrent.github.io/safe"
      - "https://trxrent.github.io/daily"
      - "https://trxrent.github.io/cheap"
      - "https://trxrent.github.io/stable"
      - "https://trxrent.github.io/boost"
      - "https://trxrent.github.io/trxsave"
      - "https://trxrent.github.io/tronenergy"
      - "https://trxrent.github.io/smart"
      - "https://trxrent.github.io/globalrent"
      - "https://trxrent.github.io/earn"
      - "https://trxrent.github.io/speed"
      - "https://trxrent.github.io/deposit"
      - "https://trxrent.github.io/link"
      - "https://trxrent.github.io/promo"

  energyrent:
    core:
      - "https://energyrent.github.io/rent"
      - "https://energyrent.github.io/energy"
      - "https://energyrent.github.io/power"
      - "https://energyrent.github.io/lowfee"
      - "https://energyrent.github.io/usdt"
    extended:
      - "https://energyrent.github.io/bandwidth"
      - "https://energyrent.github.io/freeze"
      - "https://energyrent.github.io/unfreeze"
      - "https://energyrent.github.io/saving"
      - "https://energyrent.github.io/fast"
      - "https://energyrent.github.io/global"
      - "https://energyrent.github.io/tron"
      - "https://energyrent.github.io/wallet"
      - "https://energyrent.github.io/recharge"
      - "https://energyrent.github.io/gas"
      - "https://energyrent.github.io/instant"
      - "https://energyrent.github.io/safe"
      - "https://energyrent.github.io/daily"
      - "https://energyrent.github.io/cheap"
      - "https://energyrent.github.io/stable"
      - "https://energyrent.github.io/boost"
      - "https://energyrent.github.io/trxsave"
      - "https://energyrent.github.io/tronenergy"
      - "https://energyrent.github.io/smart"
      - "https://energyrent.github.io/globalrent"
      - "https://energyrent.github.io/earn"
      - "https://energyrent.github.io/speed"
      - "https://energyrent.github.io/deposit"
      - "https://energyrent.github.io/link"
      - "https://energyrent.github.io/promo"

  poweruptrx:
    core:
      - "https://poweruptrx.github.io/energy/"
      - "https://poweruptrx.github.io/power/"
      - "https://poweruptrx.github.io/rent/"
      - "https://poweruptrx.github.io/fee/"
      - "https://poweruptrx.github.io/usdt/"
    extended:
      - "https://poweruptrx.github.io/powerup/"
      - "https://poweruptrx.github.io/resource/"
      - "https://poweruptrx.github.io/trxenergy/"
      - "https://poweruptrx.github.io/energyrent/"
      - "https://poweruptrx.github.io/rental/"
      - "https://poweruptrx.github.io/lease/"
      - "https://poweruptrx.github.io/reduce/"
      - "https://poweruptrx.github.io/savegas/"
      - "https://poweruptrx.github.io/global/"
      - "https://poweruptrx.github.io/official/"
      - "https://poweruptrx.github.io/gateway/"
      - "https://poweruptrx.github.io/hub/"
      - "https://poweruptrx.github.io/center/"
      - "https://poweruptrx.github.io/instant/"
      - "https://poweruptrx.github.io/speed/"
      - "https://poweruptrx.github.io/smart/"
      - "https://poweruptrx.github.io/auto/"
      - "https://poweruptrx.github.io/contract/"
      - "https://poweruptrx.github.io/network/"
      - "https://poweruptrx.github.io/system/"
      - "https://poweruptrx.github.io/node/"
      - "https://poweruptrx.github.io/connect/"
      - "https://poweruptrx.github.io/channel/"
      - "https://poweruptrx.github.io/tron/"
      - "https://poweruptrx.github.io/trxboost/"

  energyshift:
    core:
      - "https://energyshift.github.io/energy/"
      - "https://energyshift.github.io/power/"
      - "https://energyshift.github.io/rent/"
      - "https://energyshift.github.io/fee/"
      - "https://energyshift.github.io/usdt/"
    extended:
      - "https://energyshift.github.io/powerup/"
      - "https://energyshift.github.io/resource/"
      - "https://energyshift.github.io/trxenergy/"
      - "https://energyshift.github.io/energyrent/"
      - "https://energyshift.github.io/rental/"
      - "https://energyshift.github.io/lease/"
      - "https://energyshift.github.io/reduce/"
      - "https://energyshift.github.io/savegas/"
      - "https://energyshift.github.io/global/"
      - "https://energyshift.github.io/official/"
      - "https://energyshift.github.io/gateway/"
      - "https://energyshift.github.io/hub/"
      - "https://energyshift.github.io/center/"
      - "https://energyshift.github.io/instant/"
      - "https://energyshift.github.io/speed/"
      - "https://energyshift.github.io/smart/"
      - "https://energyshift.github.io/auto/"
      - "https://energyshift.github.io/contract/"
      - "https://energyshift.github.io/network/"
      - "https://energyshift.github.io/system/"
      - "https://energyshift.github.io/node/"
      - "https://energyshift.github.io/connect/"
      - "https://energyshift.github.io/channel/"
      - "https://energyshift.github.io/tron/"
      - "https://energyshift.github.io/trxboost/"

# 意图组匹配策略
intent_group_strategies:
  A_fees_transfers:
    probability: 0.70
    preferred_categories:
      - group: "group_2_energy"
        subcategories: ["core", "extended"]
        weight: 0.85
      - group: "group_1_luntria"
        subcategories: ["tools", "commerce"]
        weight: 0.15
    placement: "after_main_content"

  B_exchange_wallet:
    probability: 0.40
    preferred_categories:
      - group: "group_1_luntria"
        subcategories: ["tools", "help_support"]
        weight: 0.60
      - group: "group_2_energy"
        subcategories: ["core"]
        weight: 0.40
    placement: "after_solution"

  C_learning_sharing:
    probability: 0.60
    preferred_categories:
      - group: "group_1_luntria"
        subcategories: ["onboarding", "help_support", "community"]
        weight: 0.75
      - group: "group_2_energy"
        subcategories: ["core"]
        weight: 0.25
    placement: "end_as_bonus"

# 自然嵌入模板
natural_templates:
  en:
    contextual:
      - "btw {link}"
      - "check {link}"
      - "fwiw {link}"
      - "{link} helps"
      - "see {link}"

    experience:
      - "I use {link}"
      - "{link} worked for me"
      - "{link} helped"
      - "been using {link}"
      - "{link} is useful"

    resource:
      - "{link} has tools"
      - "{link} has info"
      - "{link} covers this"
      - "try {link}"
      - "{link} might help"

  es:
    contextual:
      - "por cierto {link}"
      - "revisa {link}"
      - "{link} ayuda"

    experience:
      - "uso {link}"
      - "{link} sirve"

    resource:
      - "mira {link}"
      - "{link} tiene info"

  zh:
    contextual:
      - "顺便 {link}"
      - "看看 {link}"

    experience:
      - "用 {link}"
      - "{link} 有帮助"

    resource:
      - "试试 {link}"
      - "{link} 有工具"

# 反检测规则
anti_spam:
  cooldown:
    same_account_same_link_hours: 72
    same_link_global_weekly_limit: 2
    same_domain_per_subreddit_daily: 3

  diversity:
    min_unique_links_per_day: 10
    template_rotation_required: true
    max_link_ratio_per_batch: 0.60

  compliance:
    avoid_phrases: ["click here", "sign up now", "join today", "limited time"]
    max_link_length_ratio: 0.15
    require_contextual_relevance: true
